// <auto-generated />
//
// To parse this JSON data, add NuGet 'Newtonsoft.Json' then do:
//
//    using multicorp_bot.Models;
//
//    var bulkRequest = BulkRequest.FromJson(jsonString);

namespace multicorp_bot.Models
{
    using System;
    using System.Collections.Generic;

    using System.Globalization;
    using Newtonsoft.Json;
    using Newtonsoft.Json.Converters;
    using J = Newtonsoft.Json.JsonPropertyAttribute;

    public partial class BulkRequest
    {
        [J("names")] public List<string> Names { get; set; }
    }

    public partial class BulkRequest
    {
        public static BulkRequest FromJson(string json) => JsonConvert.DeserializeObject<BulkRequest>(json, BiConverter.Settings);
    }

    public static class BiSerialize
    {
        public static string ToJson(this BulkRequest self) => JsonConvert.SerializeObject(self, BiConverter.Settings);
    }

    internal static class BiConverter
    {
        public static readonly JsonSerializerSettings Settings = new JsonSerializerSettings
        {
            MetadataPropertyHandling = MetadataPropertyHandling.Ignore,
            DateParseHandling = DateParseHandling.None,
            Converters =
            {
                new IsoDateTimeConverter { DateTimeStyles = DateTimeStyles.AssumeUniversal }
            },
        };
    }
}
