// <auto-generated />
//
// To parse this JSON data, add NuGet 'Newtonsoft.Json' then do:
//
//    using multicorp_bot.Models;
//
//    var fleetParse = FleetParse.FromJson(jsonString);

namespace multicorp_bot.Models
{
    using System;
    using System.Collections.Generic;

    using System.Globalization;
    using Newtonsoft.Json;
    using Newtonsoft.Json.Converters;
    using J = Newtonsoft.Json.JsonPropertyAttribute;
    using R = Newtonsoft.Json.Required;
    using N = Newtonsoft.Json.NullValueHandling;

    public partial class LoanerShip
    {
        [J("loaned")] public FleetParse Loaned { get; set; }
        [J("quantity")] public long Quantity { get; set; }
    }

    public partial class FleetParse
    {
        [J("id")] public string Id { get; set; }
        [J("name")] public string Name { get; set; }
        [J("chassis")] public Chassis Chassis { get; set; }
        [J("holdedShips", NullValueHandling = N.Ignore)] public List<dynamic> HoldedShips { get; set; }
        [J("loanerShips", NullValueHandling = N.Ignore)] public List<LoanerShip> LoanerShips { get; set; }
        [J("height")] public double? Height { get; set; }
        [J("length")] public double? Length { get; set; }
        [J("beam")] public double? Beam { get; set; }
        [J("maxCrew")] public long MaxCrew { get; set; }
        [J("minCrew")] public long MinCrew { get; set; }
        [J("readyStatus")] public string ReadyStatus { get; set; }
        [J("size")] public string Size { get; set; }
        [J("cargoCapacity")] public long CargoCapacity { get; set; }
        [J("career")] public Career Career { get; set; }
        [J("roles")] public List<Career> Roles { get; set; }
        [J("pledgeUrl")] public Uri PledgeUrl { get; set; }
        [J("pledgeCost")] public long? PledgeCost { get; set; }
        [J("createdAt")] public DateTimeOffset CreatedAt { get; set; }
        [J("updatedAt")] public DateTimeOffset UpdatedAt { get; set; }
        [J("pictureUri")] public Uri PictureUri { get; set; }
        [J("thumbnailUri")] public Uri ThumbnailUri { get; set; }
    }

    public partial class Career
    {
        [J("id")] public string Id { get; set; }
        [J("label")] public string Label { get; set; }
    }

    public partial class Chassis
    {
        [J("id")] public string Id { get; set; }
        [J("name")] public string Name { get; set; }
        [J("manufacturer")] public Manufacturer Manufacturer { get; set; }
    }

    public partial class Manufacturer
    {
        [J("id")] public string Id { get; set; }
        [J("name")] public string Name { get; set; }
        [J("code")] public string Code { get; set; }
        [J("logoUri")] public Uri LogoUri { get; set; }
    }

    public partial class FleetParse
    {
        public static List<FleetParse> FromJson(string json) => JsonConvert.DeserializeObject<List<FleetParse>>(json, multicorp_bot.Models.Converter.Settings);
    }

    public static class Serialize
    {
        public static string ToJson(this List<FleetParse> self) => JsonConvert.SerializeObject(self, multicorp_bot.Models.Converter.Settings);
    }

    internal static class Converter
    {
        public static readonly JsonSerializerSettings Settings = new JsonSerializerSettings
        {
            MetadataPropertyHandling = MetadataPropertyHandling.Ignore,
            DateParseHandling = DateParseHandling.None,
            Converters =
            {
                new IsoDateTimeConverter { DateTimeStyles = DateTimeStyles.AssumeUniversal }
            },
        };
    }
}
